### ISSUE TITLE
Issues on password 

### ISSUE THREAD

**Issue by sharanyaks06** [ashawe/Safana#13]
We used the same user ID as suggested but it's saying wrong password. We tried both of the user ID and password given still sane issue. Can you please help me in that

**Comment by sharanyaks06** [comment]
We tried to install the apk in phone ..it works fine but...it's asking login credentials. 
For example the user login ID is  SUP001..
but the pwd is not correct..
How do we tackle that problem

**Comment by sharanyaks06** [comment]
Is it because of wrong password?

**Comment by ashawe** [comment]
The demo apk won't work because it uses a database that isn't live.

You'd have to create your own database in firebase to make it work. I'll post the sample firebase database for you to recreate it soon.

**Comment by ashawe** [comment]
![image](https://github.com/ashawe/Safana/assets/19408070/aa0338b9-4c76-49dd-82c1-a12290e2ce03)
