### ISSUE TITLE
i cant connect firebase in this application

### ISSUE THREAD

**Issue by hackernm99** [ashawe/Safana#9]
its login screen only showing loader

**Comment by ashawe** [comment]
Did you setup firebase correcly?

Our firebase project might be out of date. You might need to create a new project, set it up in the app and then register

**Comment by hackernm99** [comment]
Bro I tried everything when I created new project and changed package name and changed Google services.json then app worked. Properly but I can't getting register or login may be there is an issue in firebase storage rules or maybe there is an error in your application because when I changed firebase rules to public access then application showing me user doesn't exist , and when I created a user manually in collection and document then whenever I entered that user which I manually created application forced stops , so there is measure issue in application , can you help me.
??

**Comment by ashawe** [comment]
> 
> 
> Bro I tried everything when I created new project and changed package name and changed Google services.json then app worked. Properly but I can't getting register or login may be there is an issue in firebase storage rules or maybe there is an error in your application because when I changed firebase rules to public access then application showing me user doesn't exist , and when I created a user manually in collection and document then whenever I entered that user which I manually created application forced stops , so there is measure issue in application , can you help me.
> ??

Sure, I'll look into it

**Comment by hackernm99** [comment]
> > Bro I tried everything when I created new project and changed package name and changed Google services.json then app worked. Properly but I can't getting register or login may be there is an issue in firebase storage rules or maybe there is an error in your application because when I changed firebase rules to public access then application showing me user doesn't exist , and when I created a user manually in collection and document then whenever I entered that user which I manually created application forced stops , so there is measure issue in application , can you help me.
> > ??
> 
> Sure, I'll look into it. Can you share your project and give me access to that firebase project?

yes sure bro.
bro can you give me any hint how to setup firebase please because I've tried everything

**Comment by hackernm99** [comment]
> > Bro I tried everything when I created new project and changed package name and changed Google services.json then app worked. Properly but I can't getting register or login may be there is an issue in firebase storage rules or maybe there is an error in your application because when I changed firebase rules to public access then application showing me user doesn't exist , and when I created a user manually in collection and document then whenever I entered that user which I manually created application forced stops , so there is measure issue in application , can you help me.
> > ??
> 
> Sure, I'll look into it. Can you share your project and give me access to that firebase project?

W/hstudios.safan: Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/hstudios.safan: Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
W/Firestore: (0.6.6-dev) [Firestore]: Listen for Query(Employees/SUP001) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}

**Comment by hackernm99** [comment]
when I changed 
Change allow read, write: if false; to true;
its finally showing me some kinda toast message 

It showing **User Doesn't exist**
now what to do BRO ??

**Comment by ashawe** [comment]
> It showing **User Doesn't exist**
> now what to do BRO ??

You have to register first before logging in...
Since this isn't our firestore database, there is no SUP001 user in the database.

You need to create a collection in the database like shown [here](https://github.com/ashawe/Safana#sample-firebase-data)(Allowances, Employees, Leaves, Logs, Projects, Tasks)

Then, try registering through the application

**Comment by hackernm99** [comment]
But how bro I mean how I can register SUP001 ?
PLEASE elaborate brother ?

**Comment by ashawe** [comment]
@hackernm99 Sure, so follow these steps:
1. Go to your firebase project (console.firebase.google.com) > Cloud firestore.
2. Select the server location.
3. Click on Start Collection.
4. Name it "Employees" (exactly as it is 'e' is capital) and then click on next
5. give the document id as SUP001 (or the username you want to login with as a supervisor)
6. in the field section write: password and in value write sup001 (or any other password you want)
7. Similarly add name, email and mobile fields (and their values)
8. click on save.
9. Now try to login using the credentials you entered into the account

**Comment by ashawe** [comment]
> 
> Thank you brother , appreciate that

If it is working, you might be able to see some sample data. You can now create employees and they should be able to log in.

Keep in mind that some features like
1. Bringing list of employees from database
2. List of tasks from database
aren't implemented yet.

**Comment by hackernm99** [comment]
Thanks, I'll check it out Bro

**Comment by prince2755** [comment]
hi, bro Enter id my kay write Karu ?????

**Comment by ashawe** [comment]
> 
> 
> hi, bro Enter id my kay write Karu ?????

Make sure you setup your firebase first before using the app. See the steps above for more info.

**Comment by prince2755** [comment]
firebase firestore dependency old
but new  dependency Add Error (setTimestampsInSnapshotsEnabled(true) )
Error ?????

**Comment by ngocbach99** [comment]
I was able to login to the demo, but can't work with the software, can you give me the database details to modify?

**Comment by ngocbach99** [comment]
I just want to know how it works, not for commercial purposes

**Comment by ashawe** [comment]
The problem is that I don't have the database now so you need to recreate it.

**Comment by jaymakwana1432** [comment]
hii sir i download our safana zip file and create project in fire base and i change the google servies file

after that how i download the app
pls show me
